### ISSUE TITLE
Not able to load plugin ERROR no such file or directory

### ISSUE THREAD

**Issue by anujp** [controlplaneio/kubectl-kubesec#19]
Hi. 
I'm trying to run the plugin from inside a pod.  But i keep getting error 

```
~ # kubectl scan
no such file or directory
~ #
```

My setup : 
Alpine3.9 based container. 
Kubectl version - 1.14.0
Go version - go1.11.5 

Here is some more output to cover the details in the setup. 

```
~ # which kubectl
/usr/local/bin/kubectl

~ # kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
~ #

~ # cd ~/.kube/plugins/scan/

~/.kube/plugins/scan # ls
kubectl-scan  plugin.yaml

~/.kube/plugins/scan # kubectl plugin list
The following compatible plugins are available:

/root/.kube/plugins/scan/kubectl-scan

~/.kube/plugins/scan # echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.kube/plugins/scan
~/.kube/plugins/scan #

~/.kube/plugins/scan # kubectl scan pod anujtest1-dc657fcf4-k8v8h
no such file or directory
~/.kube/plugins/scan #

```

I dont have the option of using krew in my environment at the moment. 
Hoping for some help with this.

**Comment by poornimaram88** [comment]
Are there any updates on this issue? I'm facing the same thing inside a container

**Comment by poornimaram88** [comment]
@anujp If you have solved this, pls let me know

**Comment by 06kellyjac** [comment]
You're trying to run a dynamically compiled binary that links to libc on a distribution that uses musl.

```
$ file ./scan
./scan: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=Wz0k20LvC36hDValbVr_/z4AlhHLHkjtw7oM5uXVe/17Qso1bEtrMTBdlUbE2d/LUvOKvaimSloc5HBR-z2, stripped
```

`libc6-compat` can help you out here


```bash
$ apk add -U wget
$ wget https://github.com/controlplaneio/kubectl-kubesec/releases/download/1.0.0/kubectl-kubesec_1.0.0_linux_amd64.tar.gz
$ tar xvf kubectl-kubesec_1.0.0_linux_amd64.tar.gz
$ ls -al ./scan
-rwxrwxr-x    1 2000     2000      25699840 Dec 28  2018 ./scan
# You'll see it's executable
$ ./scan
/bin/sh: ./scan: not found
# But it doesn't run..
$ apk add -U libc6-compat
$ ./scan
panic: error obtaining kubectl config: the provided credentials "/root/.kube/config" could not be loaded: stat /root/.kube/config: no such file or directory

goroutine 1 [running]:
github.com/stefanprodan/kubectl-kubesec/pkg/cmd.loadConfig(0xc0000d8500)
	/home/travis/gopath/src/github.com/stefanprodan/kubectl-kubesec/pkg/cmd/root.go:44 +0x5e
github.com/stefanprodan/kubectl-kubesec/pkg/cmd.init.0()
	/home/travis/gopath/src/github.com/stefanprodan/kubectl-kubesec/pkg/cmd/root.go:30 +0xb2
# Tada, now it runs.
```

full run:

```bash
$ apk add -U curl libc6-compat
$ curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
$ chmod +x ./kubectl
$ sudo mv ./kubectl /usr/local/bin/kubectl
$ mv ./kubectl /usr/local/bin/kubectl
$ curl -LO "https://github.com/controlplaneio/kubectl-kubesec/releases/download/1.0.0/kubectl-kubesec_1.0.0_linux_amd64.tar.gz"
$ tar xvf kubectl-kubesec_1.0.0_linux_amd64.tar.gz
$ mv scan /usr/local/bin/kubectl-scan
$ mv plugin.yaml /usr/local/bin/
$ kubectl scan
kubesec.io command line utilities

Usage:
  scan [command]

Available Commands:
  daemonset   Scans daemonset object
  deployment  Scans deployment object
  help        Help about any command
  pod         Scans pod object
  statefulset Scans statefulset object
  version     Prints kubesec version

Flags:
  -h, --help               help for scan
  -n, --namespace string   Kubernetes namespace (default "default")

Use "scan [command] --help" for more information about a command.
```

But as a note when I tried to scan a deployment I got the following message: `scanning deployment nginx in namespace default. the server could not find the requested resource`

`kubectl-kubesec` is quite behind normal `kubesec` and needs quite a bit of love. You might get better results for now doing:
`kubectl get deploy something -o yaml | kubesec scan -` with a modern version of `kubesec`

**Comment by poornimaram88** [comment]
Awesome! thank you very much :) @06kellyjac 

Yes, I'm creating a solution with kubesec - which will scan yaml files directly as one option and if given will also scan kube objects (in the absence of source yamls). that's the reason I'm going for the plugin too. 

Will this help in extracting yaml with accuracy?( - kubectl get deploy something -o yaml). 
Which will be a better option?

**Comment by 06kellyjac** [comment]
I havent had a particularly deep look at the code but id imagine that's functionally all it does under the hood + the nice interface through kubectl

If kubectl-kubesec was up to date it wouldn't really matter but since it's behind id recommend the `-o yaml |...` method for now

**Comment by jdflament** [comment]
@06kellyjac thanks a lot you made my day :pray:

**Comment by spiarh** [comment]
Closing as this issue is resolved.
